###  BUG: Receiving files from external apps display an error

#### Pr: https://github.com/owncloud/android/pull/1598

Devices:

Server:


---

 
| TestID | Test Case | Steps | Expected Result | Result | Related Comment |
| :----: | :-------- | :---- | :-------------- | :----: | :-------------- |
|**External apps**||||||
| 1 | Google Drive | Open the app and share a file with ownCloud|File is correctly shared and stored in ownCloud| | |
| 2 | ListMyApps | Open the app and share a file with ownCloud|File is correctly shared and stored in ownCloud| | |
| 3 | Gtask | Open the app and share a file with ownCloud|File is correctly shared and stored in ownCloud| | |
| 4 | Moon Reader | Open the app and share a file with ownCloud|File is correctly shared and stored in ownCloud| | |
| 5 | FeedMe | Open the app and share a file with ownCloud|File is correctly shared and stored in ownCloud| | |
| 6 | Google Keep | Open the app and share a file with ownCloud|File is correctly shared and stored in ownCloud| | |
| 7 | Speed Test | Open the app and share a file with ownCloud|File is correctly shared and stored in ownCloud| | |
| 8 | Gmail | Open the app and share an attached file with ownCloud|File is correctly shared and stored in ownCloud| | |